### ISSUE TITLE
Font Color & Borders - Dark Mode

### ISSUE THREAD

**Issue by Inrixia** [RevoLand/Steam-Library-Manager#18]
Loving the new version! This isnt a issue just a request... Could you change the borders to be a dark grey for the dark mode... Its kinda in your face atm. Also would be nice if the main text was a little greyer and less blaring white. [![Screenshot from Gyazo](https://gyazo.com/fb21f28ed28b807fad500777967304cc/raw)](https://gyazo.com/fb21f28ed28b807fad500777967304cc)

**Comment by RevoLand** [comment]
Thank you for your request. I've a better idea and i think you will like too. 

Instead of editing the pre-defined color accents by [mahapps.metro](https://github.com/MahApps/MahApps.Metro), i will add a Custom option and letting users pick colors for everything with a color picker which should be a win-win for everyone 😄 

If everything goes smooth and nothing else comes up, that should be up by tonight.

**Comment by Inrixia** [comment]
Awesome! Thanks again for making such a great program, its been soo useful. Keep up the amazing work 👍

You can close then when you like.

**Comment by RevoLand** [comment]
Thanks to you :) 

I've successfully implemented it in v1.5.0.6, please let me know if anything goes wrong or not works as intended.

(P.S. Text color of groupbox header is can not be changed atm)
