### ISSUE TITLE
Redistributable Cleaner

### ISSUE THREAD

**Issue by Chaython** [RevoLand/Steam-Library-Manager#47]
https://github.com/jonathanlermitage/tikione-steam-cleaner
Tiki-one has been canceled as steam has started shared redistributables, and launchers such as origin often redownload them anyways.
But maybe a good feature for SLM
In my 5tb of games, I had 112gb of redistributables. Should be significantly less as more games use steam's shared redists.

**Comment by RevoLand** [comment]
Hello, sorry for a late reply.

This is another long-term goal i have already set. Rather than removing/deleting the files, i were planning to unify them with the power of symlink, name and md5 comparison etc.

To give more details about what's in my mind;
- Let user chose a folder to keep redistributables in,
- Compare available redistributable files by name and md5 checksum, copy them to the chosen folder with the same or a different name (prefix or suffix)
- Link the redistributable files with symlink to the new generated files

In this way, Steam shouldn't bug users on verifications or updates yet users would still save space.

However, it is the lowest priority item in the to-do list, still thank you for the suggestion and let me know if this can be improved.
